### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer on GET with large response length

### ISSUE THREAD

**Issue by cjjuice** [socrata/soda-ruby#51]
When performing a GET where the response is over a certain length, we have been getting this error out of data.medicare.gov ? Anyone else having this issue? 

```ruby
Errno::ECONNRESET: Connection reset by peer
/usr/local/lib/ruby/2.5.0/openssl/buffering.rb:182:in `sysread_nonblock'
/usr/local/lib/ruby/2.5.0/openssl/buffering.rb:182:in `read_nonblock'
/usr/local/lib/ruby/2.5.0/net/protocol.rb:175:in `rbuf_fill'
/usr/local/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
```

**Comment by cjjuice** [comment]
If I reduce the `$limit` param down to `50` it works but anything over results in the error.
